name: focustube
description: "FocusTube - Time-based YouTube access control app with educational features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # YouTube integration
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.3.1
  
  # Time and date management
  intl: ^0.19.0
  
  # Local storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Permissions and device access
  permission_handler: ^11.3.1
  device_apps: ^2.2.0
  usage_stats: ^1.3.0
  
  # UI components
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  
  # HTTP requests
  http: ^1.2.2
  
  # JSON handling
  json_annotation: ^4.9.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/quotes/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

